services:
  api:
    container_name: universallychallenged_dev_api
    ports: 
      - 3000:3000
    environment: 
      - PGUSER=universallychallenged
      - PGHOST=db
      - PGPASSWORD=quizpass
      - PGDATABASE=quiz
      - PGPORT=5432
      - NODE_ENV=development
    depends_on:
      - db
    command: bash -c "npm install && npm run seedDev && npm run dev"

  db:
    container_name: debug_dev_db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
    environment: 
      - POSTGRES_DB=quiz
      - POSTGRES_USER=universallychallenged
      - POSTGRES_PASSWORD=quizpass
volumes:
  dbdata:
networks: 
  default:
    name: universallychallenged_api
